/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spyr;

import com.formdev.flatlaf.FlatLightLaf;
import com.sun.tools.javac.Main;
import net.harawata.appdirs.AppDirs;
import net.harawata.appdirs.AppDirsFactory;

import javax.swing.*;
import java.io.File;

public class App {
    public static MainWindow mainWindow;
    public static AudioPlayer audioPlayer;
    static AppDirs appDirs = AppDirsFactory.getInstance();
    public static String configDir = appDirs.getUserConfigDir("Spyr", null, null);
    public static File configJson;
    public static void main(String[] args) {
        audioPlayer = new AudioPlayer();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        File configDirLocation = new File(configDir);
        File configJson = new File(configDir + "/config.json");
        try {
            configDirLocation.mkdir();
            if (configJson.createNewFile()) {
                //TODO: initial setup
            }
        } catch (Exception e) {
            System.out.println("Error creating config files! Do you have the required permissions?");
        }
        System.out.println("Configuration will be stored at " + configJson);
        mainWindow = new MainWindow();
        mainWindow.setup();
    }
}
