/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spyr;

import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        MainWindow.setup();
    }
}
